apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: diabetes-eks-cluster
  region: us-east-1

nodeGroups:
 # - name: ng-1
 #   instanceType: m5.large             
  #  desiredCapacity: 10
  - name: ng-m5-xlarge                  
    instanceType: m5.xlarge             
    desiredCapacity: 1
